# Generated by Django 2.0.1 on 2018-01-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press', models.CharField(max_length=100)),
                ('cmt_text', models.TextField()),
                ('cmt_date', models.DateTimeField()),
                ('cmt_recom', models.IntegerField()),
                ('cmt_unrecom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News_analyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_cloud', models.ImageField(blank=True, upload_to='wordcloud')),
                ('rep_cmt_1', models.CharField(max_length=200)),
                ('rep_cmt_2', models.CharField(max_length=200)),
                ('rep_cmt_3', models.CharField(max_length=200)),
                ('positive_cmt', models.IntegerField()),
                ('negative_cmt', models.IntegerField()),
                ('neutral_cmt', models.IntegerField()),
                ('portal', models.CharField(choices=[('Naver', 'Naver'), ('Daum', 'Daum')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='News_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('press', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('세계', '세계'), ('생활', '생활'), ('문화', '문화'), ('정치', '정치'), ('기타', '기타'), ('경제', '경제'), ('사회', '사회'), ('IT', 'IT')], max_length=10)),
                ('url_naver', models.URLField()),
                ('url_daum', models.URLField()),
                ('thumbnail', models.URLField(blank=True)),
                ('date', models.DateField()),
                ('collect_cmt_naver', models.BooleanField(default=False)),
                ('collect_cmt_daum', models.BooleanField(default=False)),
                ('analyze_naver', models.BooleanField(default=False)),
                ('analyze_daum', models.BooleanField(default=False)),
                ('gap_ratio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news_analyze',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newscompare.News_list'),
        ),
        migrations.AddField(
            model_name='comment_buffer',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Newscompare.News_list'),
        ),
    ]
