# Generated by Django 2.0.1 on 2018-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0003_auto_20180129_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='word_cloud',
            field=models.ImageField(blank=True, upload_to='wordcloud/'),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('정치', '정치'), ('세계', '세계'), ('경제', '경제'), ('사회', '사회'), ('생활', '생활'), ('문화', '문화'), ('기타', '기타'), ('IT', 'IT')], max_length=10),
        ),
    ]
