# Generated by Django 2.0.1 on 2018-02-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0004_auto_20180204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='negative_cmt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='neutral_cmt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='portal',
            field=models.CharField(choices=[('Daum', 'Daum'), ('Naver', 'Naver')], max_length=10),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='positive_cmt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='rep_cmt_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='rep_cmt_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='rep_cmt_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('정치', '정치'), ('문화', '문화'), ('사회', '사회'), ('경제', '경제'), ('생활', '생활'), ('기타', '기타'), ('IT', 'IT'), ('세계', '세계')], max_length=10),
        ),
    ]
