# Generated by Django 2.0.1 on 2018-02-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0005_auto_20180204_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='negative_cmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='neutral_cmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='positive_cmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('사회', '사회'), ('경제', '경제'), ('IT', 'IT'), ('정치', '정치'), ('기타', '기타'), ('문화', '문화'), ('생활', '생활'), ('세계', '세계')], max_length=10),
        ),
    ]
