# Generated by Django 2.0.1 on 2018-02-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0006_auto_20180205_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='portal',
            field=models.CharField(choices=[('Naver', 'Naver'), ('Daum', 'Daum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('세계', '세계'), ('사회', '사회'), ('문화', '문화'), ('기타', '기타'), ('경제', '경제'), ('IT', 'IT'), ('정치', '정치'), ('생활', '생활')], max_length=10),
        ),
    ]
