# Generated by Django 2.0.1 on 2018-02-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0007_auto_20180205_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='word_cloud',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('경제', '경제'), ('세계', '세계'), ('기타', '기타'), ('IT', 'IT'), ('정치', '정치'), ('사회', '사회'), ('생활', '생활'), ('문화', '문화')], max_length=10),
        ),
    ]
