# Generated by Django 2.0.1 on 2018-02-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0008_auto_20180210_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analyze',
            name='portal',
            field=models.CharField(choices=[('Daum', 'Daum'), ('Naver', 'Naver')], max_length=10),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='word_cloud',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('문화', '문화'), ('세계', '세계'), ('정치', '정치'), ('IT', 'IT'), ('생활', '생활'), ('기타', '기타'), ('사회', '사회'), ('경제', '경제')], max_length=10),
        ),
    ]
