# Generated by Django 2.0.1 on 2018-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0009_auto_20180210_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_analyze',
            old_name='rep_cmt_1',
            new_name='rep_cmt',
        ),
        migrations.RemoveField(
            model_name='news_analyze',
            name='rep_cmt_2',
        ),
        migrations.RemoveField(
            model_name='news_analyze',
            name='rep_cmt_3',
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('정치', '정치'), ('문화', '문화'), ('사회', '사회'), ('기타', '기타'), ('세계', '세계'), ('IT', 'IT'), ('경제', '경제'), ('생활', '생활')], max_length=10),
        ),
    ]
