# Generated by Django 2.0.1 on 2018-02-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0012_auto_20180224_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('세계', '세계'), ('정치', '정치'), ('IT', 'IT'), ('기타', '기타'), ('문화', '문화'), ('경제', '경제'), ('사회', '사회'), ('생활', '생활')], max_length=10),
        ),
    ]
