# Generated by Django 2.0.1 on 2018-02-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newscompare', '0013_auto_20180225_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_list',
            name='analyze_daum',
        ),
        migrations.RemoveField(
            model_name='news_list',
            name='analyze_naver',
        ),
        migrations.AddField(
            model_name='news_list',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news_analyze',
            name='portal',
            field=models.CharField(blank=True, choices=[('Naver', 'Naver'), ('Daum', 'Daum')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='news_list',
            name='section',
            field=models.CharField(choices=[('경제', '경제'), ('문화', '문화'), ('정치', '정치'), ('IT', 'IT'), ('기타', '기타'), ('생활', '생활'), ('사회', '사회'), ('세계', '세계')], max_length=10),
        ),
    ]
